name: PlayerWarpGUI
version: 1.3.5
description: PlayerWarpGUI
author: judgetread
authors: [judgetread] 
website: http://thelasthero.net
main: PlayerWarpGUI.PlayerWarpGUI
depend: [Vault]
softdepend: [GriefPrevention, worldguard, WorldGuard, RedProtect]
commands:
   playerwarps:
      description: Set and go to player warps.
      aliases: [pwarps, pwarp, playerwarp]  