name: PlayerWarpGUI
version: 0.1.dev
description: PlayerWarpGUI
author: judgetread
authors: [judgetread] 
website: http://thelasthero.net
main: PlayerWarpGUI.PlayerWarpGUI
depend: [Vault]
commands:
   playerwarps:
      description: Set and go to player warps.
      aliases: [pwarps, pwarp, playerwarp]  